# Generated by Django 5.1.3 on 2024-11-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_cotizacion', models.CharField(choices=[('offset', 'Offset'), ('digital', 'Digital'), ('gran_formato', 'Gran Formato')], max_length=20)),
                ('es_pliego', models.BooleanField(default=False)),
                ('oculto', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
            ],
            options={
                'unique_together': {('producto', 'material')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='materiales',
            field=models.ManyToManyField(through='products.ProductoMaterial', to='products.material'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sector'),
        ),
    ]
