# Generated by Django 5.1.3 on 2024-12-04 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(10000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangoCantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_inicio', models.PositiveIntegerField()),
                ('rango_fin', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(100000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(to='productos.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cotizadores',
            field=models.ManyToManyField(to='productos.cotizador'),
        ),
        migrations.AddField(
            model_name='producto',
            name='rangos_cantidad',
            field=models.ManyToManyField(to='productos.rangocantidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sectores',
            field=models.ManyToManyField(to='productos.sector'),
        ),
        migrations.AddField(
            model_name='producto',
            name='terminaciones',
            field=models.ManyToManyField(to='productos.terminacion'),
        ),
    ]
